// Generated by scripts/extract-counties.mjs from usa_counties.svg
// (Wikimedia "Usa_counties_large.svg", U.S. Census Bureau shapes, CC0).
// DO NOT EDIT — rerun the script instead.

/** District of Columbia: county name -> rough shape path (map coordinates). */
export const DC_COUNTIES = {
  "Washington": 'M856.36 257.56 857.34 255.96 858.26 256.43 860.26 257.63 858.43 260.51 858.31 259.37 857.83 258.46 857.03 258.1Z',
} as const;

export type DCCountyName = keyof typeof DC_COUNTIES;
